# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 748c2e16fca13ed2267b2ceb3b880704a32fc0516bd1d7ecbad189f0f9e4f15a1416887212530ce52457506e69d74c7eb515e955acfca1a594f95f76bf5858b3

test:
  secret_key_base: 61c6ca299bf625e6618d95080f61b64d9f5f454912340273770697a6845768434dda6e1560793007ed6117ff875449e028deb48e72b58699d3fb7c1743102f45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
